name: flutube
description: Flutter plugin that facilitates the embed of YT videos without using the official YT API.
version: 0.8.3
homepage: https://github.com/ja2375/FluTube

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  http: ">= 0.12.0 <0.13.0"
  chewie:
    git: 
      url: https://github.com/puzuka/chewie.git
      ref: 945fa25d8a48dbb7d7ce9fc303804f7db52bdc04
  flutter:
    sdk: flutter

flutter:
